image: node:12

.exclude_template: &exclude_template
    except:
        changes:
            - "*.md"
cache:
    paths:
        - node_modules/

stages:
    - lint
    - test
    - build
    - deploy

before_script:
    - which ssh-agent || (apk add --update --no-cache openssh-client)
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - export SOURCE_BRANCH_SHA=`git ls-remote git@gitlab.com:infgosp/popen.git $CI_MERGE_REQUEST_TARGET_BRANCH_NAME | awk '{ print $1}'`
    - echo "$SOURCE_BRANCH_SHA"

lint:
    stage: lint
    script:
        - npm install
        - npm run ci:lint
    only:
        - merge_request
    <<: *exclude_template

test:
    stage: test
    script:
        - npm install
        - npm run ci:test
    only:
        - merge_request
    <<: *exclude_template
    artifacts:
        paths:
            - coverage/apps/
        expire_in: 1 week

regular-build:
    stage: build
    script:
        - npm install
        - npm run ci:build
    only:
        - merge_request
    <<: *exclude_template

master-build:
    stage: build
    script:
        - npm install
        - npm run all:build
    only:
        - master
    <<: *exclude_template
    artifacts:
        paths:
            - dist/apps/
        expire_in: 1 week
