image: jsokolowski/calc-ci

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

stages:
    - setup
    - lint
    - test
    - build
    - deploy

setup:
    stage: setup
    artifacts:
        paths:
            - libs/calc-rs/pkg
            - public/
        expire_in: 1 week
    script:
        - rustup default nightly
        - rustc --version
        - cargo --version
        - firefox --version
        - rustup default
        - npm install
        - npm run build:wasm
    rules:
        -   if: $CI_COMMIT_BRANCH == "master"
        -   if: $CI_MERGE_REQUEST_ID

lint:
    stage: lint
    script:
        - npm install
        - npm run ci:lint
    rules:
        -   if: $CI_MERGE_REQUEST_ID

test:
    stage: test
    script:
        - npm run ci:test
    after_script:
        - bash <(curl -s https://codecov.io/bash)
    artifacts:
        paths:
            - coverage/
        expire_in: 1 week
    rules:
        -   if: $CI_MERGE_REQUEST_ID

build:
    stage: build
    script:
        - npm run build:wasm && npm run build:prod
    rules:
        -   if: $CI_MERGE_REQUEST_ID

pages:
    stage: deploy
    artifacts:
        paths:
            - public
            - libs/calc-rs/pkg
    script:
        - npm run build:wasm && npm run build:prod
        - cp -r dist/apps/calc-web public/
    rules:
        -   if: $CI_COMMIT_BRANCH == "master"


