image: node:12

cache:
    paths:
        - node_modules/

include:
    -   template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

stages:
    - lint
    - test
    - build

lint:
    stage: lint
    script:
        - echo "CI_COMMIT_SHA" "${CI_COMMIT_SHA}"
        - echo "CI_MERGE_REQUEST_SOURCE_BRANCH_SHA" "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
        - npm install
        - npm run ci:lint

test:
    stage: test
    script:
        - npm install
        - npm run ci:test
    only:
        - merge_request
    artifacts:
        paths:
            - coverage/apps/
        expire_in: 1 week

regular-build:
    stage: build
    script:
        - npm install
        - npm run ci:build
