image: node:12

cache:
    paths:
        - node_modules/

stages:
    - lint
    - test
    - build

lint:
    stage: lint
    script:
        - npm install
        - npm run ci:lint
    only:
        - merge_request

test:
    stage: test
    script:
        - npm install
        - npm run ci:test
    only:
        - merge_request
    artifacts:
        paths:
            - coverage/apps/
        expire_in: 1 week

regular-build:
    stage: build
    script:
        - npm install
        - npm run ci:build
    only:
        - merge_request

master-build:
    stage: build
    script:
        - npm install
        - npm run all:build
    only:
        - master
    artifacts:
        paths:
            - dist/apps/
        expire_in: 1 week

master-test:
    stage: test
    script:
        - npm install
        - npm run all:test
    artifacts:
        paths:
            - coverage/
        expire_in: 1 week
    only:
        - master

