name: Master CI

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    persist-credentials: false

            -   name: Set env
                run: echo "NX_CALC_GIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV

            -   name: Install and Build
                run: |
                    echo NX_CALC_GIT_SHA: $NX_CALC_GIT_SHA
                    yarn install
                    npm run build:prod

            -   name: Deploy
                uses: JamesIves/github-pages-deploy-action@3.7.1
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: dist/apps/calc-web
                    CLEAN: true
